print("Hello There\n")
print("Welcome to the Band Name Generator.")
street = input("What is the name of the your city?\n")
pet = input("What is your pet's name?\n")
print("Your band name could be " + street + " " + pet)